import pygame
from pyo import *
from time import sleep

# Constants
NUM_CHANNELS=32
BEAT_TIME=.25
BEATS_IN_LINE=8

# Drum sounds
files = [ "../../assets/sounds/osdrumkit/chh37.ogg",
    "../../assets/sounds/osdrumkit/kick_22.ogg", 
    "../../assets/sounds/osdrumkit/sidestick24.ogg",
    "../../assets/sounds/osdrumkit/snaretop_37.ogg" 
]

sounds = []

# Drum beat
beat = [[[1, 0, 0, 0, 1, 0, 0, 0]],
        [[1, 1, 1, 1, 1, 1, 1, 1]],
        [[0, 0, 1, 0, 0, 0, 0, 0]],
        [[1, 0, 0, 0, 0, 0, 1, 0]]]


current_beat

def next_beat():
    

# Pyo initializations
server = Server().boot()
server.start()

# Pygame initializations
pygame.init()
pygame.mixer.init()
pygame.mixer.set_num_channels(NUM_CHANNELS)

# Create synchronous callbacks generated by Pyo
metronome = Metro(BEAT_TIME)
callback = TrigFunc(metronome, next_beat)

for file in files:
    new_sound = pygame.mixer.Sound(file)
    sounds.append(new_sound)

for sound in sounds:
    sound.play()

while True:
    pass

# sleep(10)

