import pygame
from pyo import *
from time import sleep

# Constants
NUM_CHANNELS=100
BEAT_TIME=.5
BEATS_IN_LINE=8

# Drum sounds
files = [ "../../assets/sounds/osdrumkit/chh37.ogg",
    "../../assets/sounds/osdrumkit/kick_22.ogg", 
    "../../assets/sounds/osdrumkit/sidestick24.ogg",
    "../../assets/sounds/osdrumkit/snaretop_37.ogg" 
]

sounds = []

# Drum beat
beat = [[[1, 0, 0, 0, 1, 0, 0, 0]],
        [[1, 1, 1, 1, 1, 1, 1, 1]],
        [[0, 0, 1, 0, 0, 0, 0, 0]],
        [[1, 0, 0, 0, 0, 0, 1, 0]]]

current_beat = 0

def next_beat():
    print "Next beat occured!"
    for sound in sounds:
        sound.play()

print "Before Pygame initializations"

# Pygame initializations
pygame.init()
pygame.mixer.init()
pygame.mixer.set_num_channels(NUM_CHANNELS)

print "After Pygame initializations"

# Create synchronous callbacks generated by Pyo
server = Server().boot()
server.start()

metronome = Metro(BEAT_TIME)
callback = TrigFunc(metronome, next_beat)
metronome.play()

print "After Pyo initializations"

for file in files:
    new_sound = pygame.mixer.Sound(file)
    sounds.append(new_sound)

print "Before 'server'"
server.gui(locals)
print "After 'server'"
# sleep(10)

